// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://coupbaltmchnhxtqdccm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvdXBiYWx0bWNobmh4dHFkY2NtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMDI0OTQsImV4cCI6MjA2MDc3ODQ5NH0.Nh_MAnzkuSTx_O6kCDx6WirYUVS2gZkjoNzT-8zSj2c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);